### ISSUE TITLE
Black has internal error with newline inside raw string

### ISSUE THREAD

**Issue by mx-psi** [psf/black#1507]
**Describe the bug** 

Black produces code that is not equivalent to source with raw strings that have an escaped newline inside.

**To Reproduce** Steps to reproduce the behavior:

The minimal example is a file with contents.

```python
example = r"\
"
```

Running black most recent master version on this file (e.g. using commit 6ebdc5a644b5e53b83a99eb93d63c91d0751da16), you get `INTERNAL ERROR: Black produced code that is not equivalent to the source.`

The contents of the log are:

```diff
--- src
+++ dst
@@ -12,10 +12,10 @@
       type_comment=
         None,  # NoneType
       value=
         Constant(
           value=
-            '\\',  # str
+            '',  # str
         )  # /Constant
     )  # /Assign
   type_ignores=
 )  # /Module
```

If ran with the `--fast` option the output is

```python
example = r""
```

**Expected behavior** A clear and concise description of what you expected to happen.

Black should produce correct code in this case.

**Environment (please complete the following information):**

- Version: 6ebdc5a644b5e53b83a99eb93d63c91d0751da16
- OS and Python version: macOS Catalina, Python 3.7.3 and Python 3.8.3

**Does this bug also happen on master?** To answer this, you have two options:

Yes

**Additional context** Add any other context about the problem here.

[Example in the wild where `black` fails](https://github.com/DataDog/datadog-agent/blob/9d77e24a21945a2aad3b09f4b61e4d595b74dfa5/tasks/system_probe.py#L188-L189)

**Comment by mx-psi** [comment]
This seems to be fixed in the latest released version

**Comment by ichard26** [comment]
It should be noted that this problem will come back when the extra string handling is reenabled by default.

**Comment by mx-psi** [comment]
> It should be noted that this problem will come back when the extra string handling is reenabled by default.

Should I reopen then?

**Comment by ichard26** [comment]
I don't know, I'll open a tracking issue for all the issues that should be fixed before the extra string handling is reenabled, but I don't know whether the individual issues should be open.

**Comment by JelleZijlstra** [comment]
I feel like we should keep any individual issues with `--experimental-string-processing` open, and perhaps organize them in a topic so we can track when we're able to turn the flag on.

**Comment by mx-psi** [comment]
Can confirm the issue still happens on latest `black` with the `--experimental-string-processing` flag.
