### ISSUE TITLE
Tab sign in function's docstring leads to error

### ISSUE THREAD

**Issue by Deejuha** [psf/black#1935]
Description
---------------
Any tabulation sign which is included in non-empty line (with minimum 1 non-whitespace character) in function-related docstring produces a bug.

Reproduction
------------------

1. Take the code
```
from typing import Any


def foo(bar: Any) -> Any:
    """
    Lorem ipsum dolor sit amet consectetur, adipisicing elit.

    Parameters
    ----------
        foo: `Any`	
            Nisi facere tempora eveniet

    Returns
    -------
        bar: `Any`
            impedit minima non corporis,

    """
    return bar
```

2. Run black with parameter aiming to above script
3. See the log
```
--- src
+++ dst
@@ -43,11 +43,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                'Lorem ipsum dolor sit amet consectetur, adipisicing elit.\n\nParameters\n----------\nfoo: `Any`\t\nNisi facere tempora eveniet\n\nReturns\n-------\nbar: `Any`\nimpedit minima non corporis,',  # str
+                'Lorem ipsum dolor sit amet consectetur, adipisicing elit.\n\nParameters\n----------\nfoo: `Any`\nNisi facere tempora eveniet\n\nReturns\n-------\nbar: `Any`\nimpedit minima non corporis,',  # str
             )  # /Constant
         )  # /Expr
         Return(
           value=
             Name(

```
4. Delete tabulation sign from line 10.
5. Run black again - black should do nothing.
6. Try moving tabulation sign to other places in this docstring.

Expected behavior
-------------------------
IMHO it should be traited same as space char.

Environment
-----------------
- Black 20.8b1
- Windows 10 / Linux mint 20.0 (captured bug on both), Python 3.9 and 3.8.5

Is bug replicable on master?
--------------------------------------
Yes :(
Latest reproduction 5d33f20

**Comment by JelleZijlstra** [comment]
Is this still reproducible on master? I thought #1810 should fix it.

**Comment by Deejuha** [comment]
Yes, it is :(

```
MINGW64 ~/workspace/black/src (master)
$ python black mytest.py
error: cannot format mytest.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\XYZ\AppData\Local\Temp\blk_navzupz4.log
Oh no! \U0001f4a5 \U0001f494 \U0001f4a5
1 file failed to reformat.

```

Reproduced on e1c86f987eca7e532f7d69f7ff4b9c70432fabbf

**Comment by jtmoon79** [comment]
Appears fixed in commit 0be7f96 (which builds `black, version 20.8b2.dev113+g0be7f96`) on March 20, 2021.

**Comment by Deejuha** [comment]
Hello @jtmoon79, thanks for the update.
I've checked the `5d33f20` and `0be7f96d9c` - this problem still occurs.
Please mind that there should be a tab sign somewhere (in the shown example there is on the line 10, col 19).

```
~/.../black/src(detached:master~1 ?:1 ✗) py black black_1935_test.py
error: cannot format black_1935_test.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: C:\Users\JuszczM2\AppData\Local\Temp\blk_ljo7mkeg.log
Oh no! \U0001f4a5 \U0001f494 \U0001f4a5
1 file failed to reformat.

```
![image](https://user-images.githubusercontent.com/31712401/112106180-a348ea80-8bad-11eb-9323-4748c61407a7.png)

**Comment by karalekas** [comment]
I also ran into this issue on `20.8b1`, but when using using `21.5b1` it appears to be resolved. 

Tested with a file that contains the following:

```python
def my_func(a, b):
    """
    Tabs	are bad.
    """
    return a + b
```

**Comment by JelleZijlstra** [comment]
The original example no longer reproduces a crash either.
