### ISSUE TITLE
Black specifies a requirement for click>=7.1.2 but actually requires click>=8.0

### ISSUE THREAD

**Issue by enpaul** [psf/black#2774]
**Describe the bug**

Installing `black` from the head of the `main` branch and `click<8.0` results in a stack trace whenever the tool is run.

**To Reproduce**

```bash
python3 -m venv black-click-compat-bug
source black-click-compat-bug/bin/activate
python -m pip install \
  "click<8.0" \
  git+https://github.com/psf/black
black --help
```

Resulting traceback:

```
Traceback (most recent call last):
  File "/home/enpaul/black-click-compat-bug/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/enpaul/black-click-compat-bug/lib64/python3.10/site-packages/black/__init__.py", line 34, in <module>
    from click.core import ParameterSource
ImportError: cannot import name 'ParameterSource' from 'click.core' (/home/enpaul/black-click-compat-bug/lib64/python3.10/site-packages/click/core.py)
```

**Expected behavior**

Black should specify a requirement for `click>=8.0.0` ([actual specification](https://github.com/psf/black/blob/main/setup.py#L100) is for `>=7.1.2`)

**Environment**

- Black's version: `21.12b1.dev40+g565f9c9`
- OS: Linux (Fedora 35)
- Python: `Python 3.10.1`

**Comment by JelleZijlstra** [comment]
Thanks for the report. This should be an easy fix and we'll fix it before the next release.

To prevent this in the future, we should test against the lowest supported version of each dependency. Is there an existing tool that can do that?

**Comment by cooperlees** [comment]
I am not aware of such a tool. A hacky way (that would create more work for maintainers) would be to just make a requirements_minimum.txt and use that maybe on one Ubuntu CI job. The action would just need to install those pinned versions before installing black and we run our CI suite and maybe integration tests with diff shades/primer to find errors like this reported behavior.

**Comment by mdgilene** [comment]
Forcing click>=8.0.0 on users for a dev dependency is pretty harsh. There are MANY application dependencies that are still locked to <=7.1.2.

Due to this I can't upgrade from the latest Black beta release.

**Comment by cooperlees** [comment]
I agree, but unfortunately, we do break with < click 8.0.0 and that breaks people and causes issue reports.

[Python Virtual environments](https://docs.python.org/3/tutorial/venv.html) could assist you here, but I have worked in large shared dependency environments and have felt your pain. I am sorry for that. Unfortunately the only other option is to bring your other CLIs in the same environment to >= click 8.0.0 that share dependencies with black.

**Comment by dashsatish** [comment]
Hi, Will this be back ported to `22.1.0` or is it gonna be a new release version? If later, when can we expect the changes in PyPI.

**Comment by JelleZijlstra** [comment]
I'm pretty sure this is fixed in 22.1.0: https://github.com/psf/black/blob/main/CHANGES.md#packaging-1

**Comment by dashsatish** [comment]
I still see the error for black 22.1.0 where click is installed as 7.1.2. Do I have to lock black with "21.12b0" till this issue is fixed?? Please let me know

**Comment by MarcoGorelli** [comment]
> 

I can't reproduce this:

```console
(venv) marcogorelli@OVMG025 tmp % pip uninstall black click -y
Found existing installation: black 22.1.0
Uninstalling black-22.1.0:
  Successfully uninstalled black-22.1.0
Found existing installation: click 8.0.1
Uninstalling click-8.0.1:
  Successfully uninstalled click-8.0.1
(venv) marcogorelli@OVMG025 tmp % pip install black==22.1.0
Collecting black==22.1.0
  Using cached black-22.1.0-cp38-cp38-macosx_10_9_x86_64.whl (1.3 MB)
Requirement already satisfied: pathspec>=0.9.0 in ./venv/lib/python3.8/site-packages (from black==22.1.0) (0.9.0)
Requirement already satisfied: tomli>=1.1.0 in ./venv/lib/python3.8/site-packages (from black==22.1.0) (1.2.3)
Requirement already satisfied: typing-extensions>=3.10.0.0 in ./venv/lib/python3.8/site-packages (from black==22.1.0) (3.10.0.0)
Requirement already satisfied: mypy-extensions>=0.4.3 in ./venv/lib/python3.8/site-packages (from black==22.1.0) (0.4.3)
Requirement already satisfied: platformdirs>=2 in ./venv/lib/python3.8/site-packages (from black==22.1.0) (2.2.0)
Collecting click>=8.0.0
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Installing collected packages: click, black
Successfully installed black-22.1.0 click-8.0.4
pip WARNING: You are using pip version 21.0.1; however, version 22.0.3 is available.
You should consider upgrading via the '/Users/marcogorelli/tmp/venv/bin/python -m pip install --upgrade pip' command.
f
%(venv) marcogorelli@OVMG025 tmp % pip freeze | grep click
click==8.0.4
```

**Comment by Duciwuci** [comment]
This didn't fix the problem.

I still got the problem with:

python: ```3.7```
black: ```22.1.0```
click: ```8.0.4```

```Traceback (most recent call last):
File "/usr/local/bin/black", line 5, in <module>
   from black import patched_main
File "src/black/__init__.py", line 35, in <module>
ImportError: cannot import name 'ParameterSource' from 'click.core' (/usr/local/lib/python3.7/site-packages/click/core.py)

**Comment by songololo** [comment]
Using `black==22.3.0` and running into the issue as well.

**Comment by asears** [comment]
Can this issue be reopened?  Similar issue with latest black and python 3.8.  If ParameterSource is not available in click core, could black downgrade gracefully?  Some dependent packages using click which are not under control.

**Comment by JelleZijlstra** [comment]
@asears Can you specify what this "similar issue" is? What versions are you running and what error are you getting?

**Comment by mtsadler-branch** [comment]
@asears https://github.com/psf/black/issues/3111
