### ISSUE TITLE
magic trailing comma not working in certain scenario

### ISSUE THREAD

**Issue by nipunn1313** [psf/black#3239]
**Describe the bug**

Trailing commas are incorrectly being ruthlessly collapsed into one line

**To Reproduce**

Reproes in the black playground
```python
def method(
    self,
) -> typing_extensions.Literal[
    "l1",
    "l2",
]: pass
```

Result is
```python
def method(
    self,
) -> typing_extensions.Literal["l1", "l2",]:
    pass
```

**Expected behavior**

I'd expect no change to the Literal writeout.

**Environment**

Black 22.6.0 in the black playground.

**Additional context**

I noticed that if we eliminate the `self` argument, then black works correctly. Seems to have something to do with the fact that there are two trailing command in the method definition. Second one is not respected.

**Comment by hauntsaninja** [comment]
I believe I've fixed this on main (you'll need to remember to use `--preview` because it's a change that changed formatting)

**Comment by nipunn1313** [comment]
at least according to https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC-AINdAD2IimZxl1N_WlbvK5V-fxcIRXBgNMb3PFjqcfxrMLJktSq6aRkCvRw96aIv09NBV5YAN_i6LoE0TXjAbbQNrVw7f1j0gc081LNWKW-py5In4PDB2yLCB7g7UtBGcgpzfVSuBjKXeq0n0j_UCcVdPayPJYNVCTnoYOpOVSTXbdZaNMEqAABhxmDJI41ybQABnwG_AQAAAG3WVrHEZ_sCAAAAAARZWg== - it doesn't seem fixed

**Comment by JelleZijlstra** [comment]
Yes, not fixed yet:

```
$ black --diff --preview tryit.py 
--- tryit.py    2022-09-02 02:02:08.120028 +0000
+++ tryit.py    2022-09-02 02:02:16.343920 +0000
@@ -1,6 +1,4 @@
 def method(
     self,
-) -> typing_extensions.Literal[
-    "l1",
-    "l2",
-]: pass
+) -> typing_extensions.Literal["l1", "l2",]:
+    pass
would reformat tryit.py

All done! ✨ 🍰 ✨
1 file would be reformatted.
$ black --version
black, 22.8.0 (compiled: yes)
Python (CPython) 3.9.12
```

(22.8.0 is the same as main right now)

**Comment by hauntsaninja** [comment]
@nipunn1313 your playground link does not check the box that says "Don't use trailing commas as a reason to split lines."
@JelleZijlstra you didn't pass `--skip-magic-trailing-comma`

```
~/dev/black main λ black --diff --preview x.py -C
--- x.py	2022-09-02 02:06:01.742586 +0000
+++ x.py	2022-09-02 02:07:53.238628 +0000
@@ -1,6 +1,2 @@
-def method(
-    self,
-) -> typing_extensions.Literal[
-    "l1",
-    "l2",
-]: pass
+def method(self) -> typing_extensions.Literal["l1", "l2"]:
+    pass
would reformat x.py

All done! ✨ 🍰 ✨
1 file would be reformatted.
```

**Comment by nipunn1313** [comment]
I want the default behavior of the magic trailing comma!

It appears that the magic trailing comma's behavior is not being respected in this case.

**Comment by hauntsaninja** [comment]
Okay, sure. Your issue title `skip_magic_trailing_comma=true` seems incorrect then?

Note that this was a trailing comma that wasn't removed with `--skip-magic-trailing-comma` until https://github.com/psf/black/pull/3209, hence my claim in https://github.com/psf/black/issues/3239#issuecomment-1229048100

**Comment by nipunn1313** [comment]
OOPS. I totally inverted my statement in the title of the task! Booleans are hard.
Editing title

**Comment by hauntsaninja** [comment]
I think your example is basically a duplicate of https://github.com/psf/black/issues/2498 which was closed as a duplicate of https://github.com/psf/black/issues/1671 although the issue title doesn't quite apply to #2498

**Comment by JelleZijlstra** [comment]
Yeah I think this is basically #1671.
